### ISSUE TITLE
Need professional opinion about a better approach to build db and models 

### ISSUE THREAD

**Issue by NovaXam** [MistyMen/musicMonster#3]
Combine tables, make a JOIN query, store data to separate tables from external API

**Comment by jasonseminara** [comment]
Thank you for opening a ticket. Please help me understand what the problem is. Please point me to code samples, etc.

**Comment by NovaXam** [comment]
we have tables 1 and table 2 in our db.
Issues:
1. When we store a data from external API to DB, this data should be separated and stored in two tables. The idea is to make two simultaneously post requests to db. code is below: 

MODEL
Music.create = music => {
  return (
    db.one(
      `
    INSERT INTO artists (name, picture)
    VALUES ($1, $2)
    RETURNING *`,
      [music.music, music.picture]
    ),
    db.one(
      `
    INSERT INTO tracks (name, url)
    VALUES ($1, $2)
    RETURNING *`,
      [music.name, music.url]
    )
  );
};    

MIGRATION

CREATE TABLE IF NOT EXISTS artists (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(1024),
  picture VARCHAR(1024),
);

CREATE TABLE IF NOT EXISTS tracks (
  id BIGSERIAL PRIMARY KEY,
  artist_id VARCHAR(1024) REFERENCES artists(id),
  name VARCHAR(1024),
  url VARCHAR(1024),
);

**Comment by NovaXam** [comment]
It looks like a solution but I am not sure that it will work. Jason, could you take a look at it. Thanks


function checker(name) {
    return db.oneOrNone(
    `
    SELECT * FROM artists
    WHERE name = $1`,
    [name]
  );

Music.create = music => {
  if(!checker(music.name)) {
    return (
      db.one(
        `
      INSERT INTO artists (name, picture)
      VALUES ($1, $2)
      RETURNING *`,
        [music.name, music.picture]
      ),
      db.one(
        `
      INSERT INTO tracks (song, url)
      VALUES ($1, $2)
      RETURNING *`,
        [music.song, music.url]
      )
    );
  } else if(checker(music.name) && !checker(music.song)) {
      return  db.one(
          `
        INSERT INTO tracks (artist_id, song, url)
        VALUES ($1, $2, $3)
        RETURNING *`,
          [music.id, music.song, music.url]
    )
  }
}
